// <auto-generated />
using System;
using English.Website.Domain.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace English.Website.Migrations
{
    [DbContext(typeof(EnglishDBContext))]
    [Migration("20260609085828_changeProp")]
    partial class changeProp
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText", b =>
                {
                    b.Property<int>("AIModelTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AIModelTextId"));

                    b.Property<string>("AIName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CacheHitPricePerMillion")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("ConcurrencyLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InputPricePerMillion")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("OutputPricePerMillion")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AIModelTextId");

                    b.ToTable("AIModelText");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AiAnalysis", b =>
                {
                    b.Property<Guid>("AiAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TokenUsageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserTranscript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AiAnalysisId");

                    b.HasIndex("TokenUsageId")
                        .IsUnique();

                    b.ToTable("AiAnalyse");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.TokenUsage", b =>
                {
                    b.Property<Guid>("TokenUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AIModelTextId")
                        .HasColumnType("int");

                    b.Property<int?>("CacheHitTokens")
                        .HasColumnType("int");

                    b.Property<int?>("CacheMissTokens")
                        .HasColumnType("int");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("int");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenUsageId");

                    b.HasIndex("AIModelTextId");

                    b.ToTable("TokenUsage");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AiAnalysis", b =>
                {
                    b.HasOne("English.Website.Domain.Entities.AI.TokenUsage", "TokenUsage")
                        .WithOne("AiAnalysis")
                        .HasForeignKey("English.Website.Domain.Entities.AI.AiAnalysis", "TokenUsageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TokenUsage");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.TokenUsage", b =>
                {
                    b.HasOne("English.Website.Domain.Entities.AI.AIModelText", "AIModel")
                        .WithMany("TokenUsages")
                        .HasForeignKey("AIModelTextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIModel");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText", b =>
                {
                    b.Navigation("TokenUsages");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.TokenUsage", b =>
                {
                    b.Navigation("AiAnalysis");
                });
#pragma warning restore 612, 618
        }
    }
}
