// <auto-generated />
using System;
using English.Website.Domain.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace English.Website.Migrations
{
    [DbContext(typeof(EnglishDBContext))]
    [Migration("20260712155156_AddFluencyErrorsJson")]
    partial class AddFluencyErrorsJson
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelAudio.AIModelAudio", b =>
                {
                    b.Property<int>("AIModelAudioId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AIModelAudioId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("PricePerHour")
                        .HasColumnType("float");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AIModelAudioId");

                    b.ToTable("AIModelAudio");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelAudio.AudioUsage", b =>
                {
                    b.Property<Guid>("AudioUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AIModelAudioId")
                        .HasColumnType("int");

                    b.Property<Guid>("AISpeechToTextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AudioUsageId");

                    b.HasIndex("AIModelAudioId");

                    b.HasIndex("AISpeechToTextId")
                        .IsUnique();

                    b.ToTable("AudioUsage");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.AIAnalysis", b =>
                {
                    b.Property<Guid>("AIAnalysisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AISpeechToTextId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnalysisContentJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("OverallGrammarScore")
                        .HasColumnType("float");

                    b.Property<double?>("OverallVocabScore")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserTranscript")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AIAnalysisId");

                    b.HasIndex("AISpeechToTextId")
                        .IsUnique()
                        .HasFilter("[AISpeechToTextId] IS NOT NULL");

                    b.ToTable("AIAnalysis");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.AIModelText", b =>
                {
                    b.Property<int>("AIModelTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AIModelTextId"));

                    b.Property<string>("AIName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("CacheHitPricePerMillion")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<int>("ConcurrencyLimit")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InputPricePerMillion")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal>("OutputPricePerMillion")
                        .HasColumnType("decimal(18, 6)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AIModelTextId");

                    b.ToTable("AIModelText");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.TokenUsage", b =>
                {
                    b.Property<Guid>("TokenUsageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AIAnalysisId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AIModelTextId")
                        .HasColumnType("int");

                    b.Property<int?>("CacheHitTokens")
                        .HasColumnType("int");

                    b.Property<int?>("CacheMissTokens")
                        .HasColumnType("int");

                    b.Property<decimal>("CalculatedCost")
                        .HasColumnType("decimal(18, 8)");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("int");

                    b.Property<int>("ReasoningTokens")
                        .HasColumnType("int");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("TokenUsageId");

                    b.HasIndex("AIAnalysisId")
                        .IsUnique()
                        .HasFilter("[AIAnalysisId] IS NOT NULL");

                    b.HasIndex("AIModelTextId");

                    b.ToTable("TokenUsage");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AISpeechToText", b =>
                {
                    b.Property<Guid>("AISpeechToTextId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AITranscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssemblyAIId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FluencyErrorsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("FluencyScore")
                        .HasColumnType("float");

                    b.Property<double?>("OverallConfidence")
                        .HasColumnType("float");

                    b.Property<string>("PhoneticTranscript")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("PronunciationScore")
                        .HasColumnType("float");

                    b.Property<Guid>("RecordingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeAnalyse")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("WordPerMinute")
                        .HasColumnType("int");

                    b.Property<string>("WordsJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WordsPronunciationScore")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AISpeechToTextId");

                    b.HasIndex("RecordingId")
                        .IsUnique();

                    b.ToTable("AISpeechToText");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.Recording", b =>
                {
                    b.Property<Guid>("RecordingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CloudinaryPublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Duration")
                        .HasColumnType("float");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("RecordingId");

                    b.ToTable("Recording");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelAudio.AudioUsage", b =>
                {
                    b.HasOne("English.Website.Domain.Entities.AI.AIModelAudio.AIModelAudio", "AIModelAudio")
                        .WithMany("AudioUsages")
                        .HasForeignKey("AIModelAudioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("English.Website.Domain.Entities.AI.AISpeechToText", "AISpeechToText")
                        .WithOne("AudioUsage")
                        .HasForeignKey("English.Website.Domain.Entities.AI.AIModelAudio.AudioUsage", "AISpeechToTextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AIModelAudio");

                    b.Navigation("AISpeechToText");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.AIAnalysis", b =>
                {
                    b.HasOne("English.Website.Domain.Entities.AI.AISpeechToText", "AISpeechToText")
                        .WithOne("AIAnalysis")
                        .HasForeignKey("English.Website.Domain.Entities.AI.AIModelText.AIAnalysis", "AISpeechToTextId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AISpeechToText");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.TokenUsage", b =>
                {
                    b.HasOne("English.Website.Domain.Entities.AI.AIModelText.AIAnalysis", "AIAnalysis")
                        .WithOne("TokenUsage")
                        .HasForeignKey("English.Website.Domain.Entities.AI.AIModelText.TokenUsage", "AIAnalysisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("English.Website.Domain.Entities.AI.AIModelText.AIModelText", "AIModelText")
                        .WithMany("TokenUsages")
                        .HasForeignKey("AIModelTextId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AIAnalysis");

                    b.Navigation("AIModelText");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AISpeechToText", b =>
                {
                    b.HasOne("English.Website.Domain.Entities.Recording", "Recording")
                        .WithOne("AISpeechToText")
                        .HasForeignKey("English.Website.Domain.Entities.AI.AISpeechToText", "RecordingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recording");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelAudio.AIModelAudio", b =>
                {
                    b.Navigation("AudioUsages");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.AIAnalysis", b =>
                {
                    b.Navigation("TokenUsage");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AIModelText.AIModelText", b =>
                {
                    b.Navigation("TokenUsages");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.AI.AISpeechToText", b =>
                {
                    b.Navigation("AIAnalysis");

                    b.Navigation("AudioUsage");
                });

            modelBuilder.Entity("English.Website.Domain.Entities.Recording", b =>
                {
                    b.Navigation("AISpeechToText");
                });
#pragma warning restore 612, 618
        }
    }
}
